[build]
  command = "npm install && npm run build"
  publish = ".next/static"
  functions = ".next/server"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 3000
  publish = ".next/static"

# Required for client-side routing in Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    publish = ".next/static"
    functions = ".next/server"
