[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 3000

# Required for client-side routing in Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
